name: NodeJS with Grunt

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']
    types:
      - opened # Trigger the workflow when a PR is opened

jobs:
  build:
    runs-on: [self-hosted, example]

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: |
          touch .env
          echo "${{ secrets.DEV_ENV }}" > .env
      - run: npm ci --legacy-peer-deps
      - run: npm run build --if-present
      - run: pm2 restart example
